Add visibility specification based on group and user URNs
DLHub-Argonne/dlhub_sdk pull request #102
Opened 2020-10-26 21:00 UTC by NathanPruyne

Modifies `set_visibility` to accept UUIDs associated with Globus Auth groups and user UUIDs via `users` and `groups` optional arguments. Without either argument the visibility will be set to public (though users desiring to make their datasets public would likely not use set_visibility). User and group UUIDs are then converted to the corresponding URNs and added to the model metadata.

Schemas have already been updated to accommodate URNs.

2020-10-27 19:12 UTC, WardLT requested changes
Looks great! Could you fix the issue I pointed out and add a unit test that adds a group/user to make sure that the resulting object validates against our JSON schema.

2020-10-27 19:12 UTC, WardLT commented on dlhub_sdk/models/__init__.py
> +    def set_visibility(self, users=[], groups=[]):
Mutable default arguments [can cause some weird errors](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments). Could you change these out for a tuple?

2020-10-30 01:38 UTC, NathanPruyne commented
@WardLT I fixed the default arguments by replacing them with None and checking for their existence later to append to the visibility specifications. Unit test has also been added to tests/test_dlhub_client.py

2020-10-30 02:17 UTC, merged

2020-10-30 02:17 UTC, WardLT commented
Thanks, @NathanPruyne !